ALTER TABLE t_p15345778_news_shop_project.shop_items
  ADD COLUMN IF NOT EXISTS is_slider BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS slider_min INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS slider_max INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS slider_step INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS unit_price INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS unit_name VARCHAR(100) NOT NULL DEFAULT '';